<?php

namespace Exception;

//exception pour un parametre invalide
class InvalideProperty extends \Exception
{
    public function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
    }
}